[package]
org = "sameera"
name = "budget_app_backend"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "budget_app_backend.db"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.1"

