[package]
org = "sameera"
name = "budget_app_backend"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "samjs"
name = "expensetracker.dbmodel"
version = "1.0.0"
repository = "local"


