[package]
org = "samjs"
name = "expensetracker.dbmodel"
version = "1.1.0"
distribution = "2201.8.5"
visibility = "private"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "expensetracker.dbmodel"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.1"
